// This file was automatically generated by noise-serde-lib.
import Foundation
import Noise
import NoiseBackend
import NoiseSerde

public enum ExecutionStep: Readable, Sendable, Writable {
  case done(ExecutionOutput)
  case more(ExecutionOutput)

  public static func read(from inp: InputPort, using buf: inout Data) -> ExecutionStep {
    let tag = UVarint.read(from: inp, using: &buf)
    switch tag {
    case 0x0000:
      return .done(
        ExecutionOutput.read(from: inp, using: &buf)
      )
    case 0x0001:
      return .more(
        ExecutionOutput.read(from: inp, using: &buf)
      )
    default:
      preconditionFailure("ExecutionStep: unexpected tag \(tag)")
    }
  }

  public func write(to out: OutputPort) {
    switch self {
    case .done(let output):
      UVarint(0x0000).write(to: out)
      output.write(to: out)
    case .more(let output):
      UVarint(0x0001).write(to: out)
      output.write(to: out)
    }
  }
}

public enum FilesystemEntry: Readable, Sendable, Writable {
  case file(File)
  case folder(Folder)

  public static func read(from inp: InputPort, using buf: inout Data) -> FilesystemEntry {
    let tag = UVarint.read(from: inp, using: &buf)
    switch tag {
    case 0x0000:
      return .file(
        File.read(from: inp, using: &buf)
      )
    case 0x0001:
      return .folder(
        Folder.read(from: inp, using: &buf)
      )
    default:
      preconditionFailure("FilesystemEntry: unexpected tag \(tag)")
    }
  }

  public func write(to out: OutputPort) {
    switch self {
    case .file(let file):
      UVarint(0x0000).write(to: out)
      file.write(to: out)
    case .folder(let folder):
      UVarint(0x0001).write(to: out)
      folder.write(to: out)
    }
  }
}

public struct ExecutionOutput: Readable, Sendable, Writable {
  public let stdout: Data
  public let stderr: Data

  public init(
    stdout: Data,
    stderr: Data
  ) {
    self.stdout = stdout
    self.stderr = stderr
  }

  public static func read(from inp: InputPort, using buf: inout Data) -> ExecutionOutput {
    return ExecutionOutput(
      stdout: Data.read(from: inp, using: &buf),
      stderr: Data.read(from: inp, using: &buf)
    )
  }

  public func write(to out: OutputPort) {
    stdout.write(to: out)
    stderr.write(to: out)
  }
}

public struct File: Readable, Sendable, Writable {
  public let path: String
  public let size: UVarint

  public init(
    path: String,
    size: UVarint
  ) {
    self.path = path
    self.size = size
  }

  public static func read(from inp: InputPort, using buf: inout Data) -> File {
    return File(
      path: String.read(from: inp, using: &buf),
      size: UVarint.read(from: inp, using: &buf)
    )
  }

  public func write(to out: OutputPort) {
    path.write(to: out)
    size.write(to: out)
  }
}

public struct Folder: Readable, Sendable, Writable {
  public let path: String

  public init(
    path: String
  ) {
    self.path = path
  }

  public static func read(from inp: InputPort, using buf: inout Data) -> Folder {
    return Folder(
      path: String.read(from: inp, using: &buf)
    )
  }

  public func write(to out: OutputPort) {
    path.write(to: out)
  }
}

public final class Backend: Sendable {
  let impl: NoiseBackend.Backend!

  init(withZo zo: URL, andMod mod: String, andProc proc: String, andBootArguments ba: BootArguments = .init()) {
    impl = NoiseBackend.Backend(withZo: zo, andMod: mod, andProc: proc, andBootArguments: ba)
  }

  public func createDirectory(atPath path: String) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0000).write(to: out)
        path.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func createDirectory(atPath path: String) async throws -> Void {
    return try await FutureUtil.asyncify(createDirectory(atPath: path))
  }

  public func deleteFile(atPath path: String) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0001).write(to: out)
        path.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func deleteFile(atPath path: String) async throws -> Void {
    return try await FutureUtil.asyncify(deleteFile(atPath: path))
  }

  public func executeScript(atPath path: String) -> Future<String, UVarint> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0002).write(to: out)
        path.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> UVarint in
        return UVarint.read(from: inp, using: &buf)
      }
    )
  }

  public func executeScript(atPath path: String) async throws -> UVarint {
    return try await FutureUtil.asyncify(executeScript(atPath: path))
  }

  public func getExecutionSymbols(_ id: UVarint) -> Future<String, [String]> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0003).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> [String] in
        return [String].read(from: inp, using: &buf)
      }
    )
  }

  public func getExecutionSymbols(_ id: UVarint) async throws -> [String] {
    return try await FutureUtil.asyncify(getExecutionSymbols(id))
  }

  public func getRootPath() -> Future<String, String> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0004).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String in
        return String.read(from: inp, using: &buf)
      }
    )
  }

  public func getRootPath() async throws -> String {
    return try await FutureUtil.asyncify(getRootPath())
  }

  public func installCallback(internalWithId id: UVarint, andAddr addr: Varint) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0005).write(to: out)
        id.write(to: out)
        addr.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func installCallback(internalWithId id: UVarint, andAddr addr: Varint) async throws -> Void {
    return try await FutureUtil.asyncify(installCallback(internalWithId: id, andAddr: addr))
  }

  public func listFiles(atPath root: String) -> Future<String, [FilesystemEntry]> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0006).write(to: out)
        root.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> [FilesystemEntry] in
        return [FilesystemEntry].read(from: inp, using: &buf)
      }
    )
  }

  public func listFiles(atPath root: String) async throws -> [FilesystemEntry] {
    return try await FutureUtil.asyncify(listFiles(atPath: root))
  }

  public func makeTempPath() -> Future<String, String> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0007).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String in
        return String.read(from: inp, using: &buf)
      }
    )
  }

  public func makeTempPath() async throws -> String {
    return try await FutureUtil.asyncify(makeTempPath())
  }

  public func markOnExecutorStepInstalled() -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0008).write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func markOnExecutorStepInstalled() async throws -> Void {
    return try await FutureUtil.asyncify(markOnExecutorStepInstalled())
  }

  public func readFile(atPath path: String) -> Future<String, String> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x0009).write(to: out)
        path.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> String in
        return String.read(from: inp, using: &buf)
      }
    )
  }

  public func readFile(atPath path: String) async throws -> String {
    return try await FutureUtil.asyncify(readFile(atPath: path))
  }

  public func save(_ content: String, to path: String) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000a).write(to: out)
        content.write(to: out)
        path.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func save(_ content: String, to path: String) async throws -> Void {
    return try await FutureUtil.asyncify(save(content, to: path))
  }

  public func stepExecution(_ id: UVarint) -> Future<String, ExecutionStep> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000b).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> ExecutionStep in
        return ExecutionStep.read(from: inp, using: &buf)
      }
    )
  }

  public func stepExecution(_ id: UVarint) async throws -> ExecutionStep {
    return try await FutureUtil.asyncify(stepExecution(id))
  }

  public func stopExecution(_ id: UVarint) -> Future<String, Void> {
    return impl.send(
      writeProc: { (out: OutputPort) in
        UVarint(0x000c).write(to: out)
        id.write(to: out)
      },
      readProc: { (inp: InputPort, buf: inout Data) -> Void in }
    )
  }

  public func stopExecution(_ id: UVarint) async throws -> Void {
    return try await FutureUtil.asyncify(stopExecution(id))
  }

  public func installCallback(onExecutorStep proc: @escaping @Sendable (UVarint) -> Void) -> Future<String, Void> {
    return NoiseBackend.installCallback(id: 0, rpc: self.installCallback(internalWithId:andAddr:)) { inp in
      var buf = Data(count: 8*1024)
      proc(
        UVarint.read(from: inp, using: &buf)
      )
    }
  }
}
